"""
seed_data.py – BASTION
======================
Realistic (fictional) sample data across all 5 tables.
30 controls, 20 evidence records, 10 findings, 8 remediation, 5 exceptions.
All NIST and CIS references are short paraphrased summaries only.
"""

import pandas as pd
from database import bulk_insert_df, init_db, is_seeded


# ---------------------------------------------------------------------------
# Controls  (30 rows)
# ---------------------------------------------------------------------------
CONTROLS = [
    # NIST SP 800-53 – Access Control
    {
        "control_id": "NIST-AC-1",
        "framework": "NIST SP 800-53",
        "control_family": "Access Control",
        "control_title": "Access Control Policy and Procedures",
        "control_description": "Organization establishes, documents, and disseminates an access control policy and supporting procedures.",
        "requirement_summary": "Written AC policy approved and communicated annually.",
        "control_owner": "Alice Johnson",
        "system_application": "Customer Identity Portal",
        "data_type": "PII",
        "implementation_status": "Implemented",
        "evidence_required": "Policy document, distribution record",
        "evidence_available": "Yes",
        "evidence_source": "Policy Repository",
        "evidence_link": "https://internal.example.com/policies/AC-001",
        "last_reviewed_date": "2025-11-01",
        "next_review_date": "2026-11-01",
        "assessor_notes": "Policy current; next review scheduled.",
    },
    {
        "control_id": "NIST-AC-2",
        "framework": "NIST SP 800-53",
        "control_family": "Access Control",
        "control_title": "Account Management",
        "control_description": "Organization manages information system accounts including creation, modification, review, and termination.",
        "requirement_summary": "Quarterly access reviews; automated provisioning/de-provisioning.",
        "control_owner": "Alice Johnson",
        "system_application": "Customer Identity Portal",
        "data_type": "PII",
        "implementation_status": "Partially Implemented",
        "evidence_required": "Access review report, provisioning logs",
        "evidence_available": "Partial",
        "evidence_source": "IAM System",
        "evidence_link": "https://internal.example.com/iam/reviews",
        "last_reviewed_date": "2025-09-15",
        "next_review_date": "2025-12-15",
        "assessor_notes": "De-provisioning process manual; no automated off-boarding workflow confirmed.",
    },
    {
        "control_id": "NIST-AC-3",
        "framework": "NIST SP 800-53",
        "control_family": "Access Control",
        "control_title": "Access Enforcement",
        "control_description": "System enforces approved authorizations for logical access to information and system resources.",
        "requirement_summary": "Role-based access control enforced; no shared admin accounts.",
        "control_owner": "Bob Martinez",
        "system_application": "Internal Admin Console",
        "data_type": "Internal Confidential",
        "implementation_status": "Not Implemented",
        "evidence_required": "RBAC configuration export, account audit",
        "evidence_available": "No",
        "evidence_source": "",
        "evidence_link": "",
        "last_reviewed_date": "2025-08-01",
        "next_review_date": "2025-11-01",
        "assessor_notes": "Shared admin account found. Remediation in progress.",
    },
    {
        "control_id": "NIST-AC-17",
        "framework": "NIST SP 800-53",
        "control_family": "Access Control",
        "control_title": "Remote Access",
        "control_description": "Organization establishes usage restrictions and monitoring for remote access connections.",
        "requirement_summary": "MFA required for all remote access; VPN session logs retained 90 days.",
        "control_owner": "Alice Johnson",
        "system_application": "Customer Identity Portal",
        "data_type": "PII",
        "implementation_status": "Implemented",
        "evidence_required": "VPN config, MFA enrollment report",
        "evidence_available": "Yes",
        "evidence_source": "VPN Dashboard",
        "evidence_link": "https://internal.example.com/vpn/config",
        "last_reviewed_date": "2025-12-01",
        "next_review_date": "2026-06-01",
        "assessor_notes": "MFA enforced via Okta. Session logs in SIEM.",
    },
    # NIST SP 800-53 – Audit and Logging
    {
        "control_id": "NIST-AU-2",
        "framework": "NIST SP 800-53",
        "control_family": "Audit and Logging",
        "control_title": "Auditable Events",
        "control_description": "Organization identifies events to be logged and coordinates with stakeholders to ensure adequate coverage.",
        "requirement_summary": "Defined audit event list; logs enabled for login, admin actions, data access.",
        "control_owner": "Carlos Lee",
        "system_application": "Security Logging Pipeline",
        "data_type": "Security Event Logs",
        "implementation_status": "Implemented",
        "evidence_required": "Audit event policy, SIEM rule set",
        "evidence_available": "Yes",
        "evidence_source": "SIEM Platform",
        "evidence_link": "https://internal.example.com/siem/rules",
        "last_reviewed_date": "2025-10-15",
        "next_review_date": "2026-04-15",
        "assessor_notes": "Audit event list reviewed and approved.",
    },
    {
        "control_id": "NIST-AU-6",
        "framework": "NIST SP 800-53",
        "control_family": "Audit and Logging",
        "control_title": "Audit Review and Analysis",
        "control_description": "Organization reviews and analyzes system audit records at defined frequencies for signs of inappropriate activity.",
        "requirement_summary": "Weekly log review; automated alerting for failed logins and privilege escalation.",
        "control_owner": "Carlos Lee",
        "system_application": "Security Logging Pipeline",
        "data_type": "Authentication Logs",
        "implementation_status": "Partially Implemented",
        "evidence_required": "Log review records, alert rule screenshots",
        "evidence_available": "Partial",
        "evidence_source": "SIEM Platform",
        "evidence_link": "",
        "last_reviewed_date": "2025-09-01",
        "next_review_date": "2025-12-01",
        "assessor_notes": "Alert rules exist but weekly review process not formally documented.",
    },
    # NIST – Encryption and Data Protection
    {
        "control_id": "NIST-SC-28",
        "framework": "NIST SP 800-53",
        "control_family": "Encryption and Data Protection",
        "control_title": "Protection of Information at Rest",
        "control_description": "System protects the confidentiality and integrity of information at rest in AWS S3 buckets and RDS databases.",
        "requirement_summary": "AES-256 envelope encryption at rest via AWS KMS Customer Managed Keys (CMK) with automated annual rotation.",
        "control_owner": "Diana Chen",
        "system_application": "AWS S3 Data Lake",
        "data_type": "PHI",
        "implementation_status": "Implemented",
        "evidence_required": "S3 Bucket Encryption configuration, AWS KMS Key Policy JSON, CloudTrail KMS decryption logs",
        "evidence_available": "Yes",
        "evidence_source": "AWS Console / Config",
        "evidence_link": "https://internal.example.com/aws/s3-encryption",
        "last_reviewed_date": "2025-11-20",
        "next_review_date": "2026-05-20",
        "assessor_notes": "S3 bucket encryption verified via AWS Config rule s3-bucket-ssl-requests-only and s3-bucket-server-side-encryption-enabled. Confirmed usage of Customer Managed Keys (CMK) with 365-day auto-rotation enabled and strict IAM key policies restricting decryption rights to authorized IAM roles.",
    },
    {
        "control_id": "NIST-SC-8",
        "framework": "NIST SP 800-53",
        "control_family": "Encryption and Data Protection",
        "control_title": "Transmission Confidentiality and Integrity",
        "control_description": "System implements cryptographic mechanisms to prevent unauthorized disclosure or modification of information in transit.",
        "requirement_summary": "TLS 1.2 or higher required for all API communications.",
        "control_owner": "Diana Chen",
        "system_application": "Payment Processing API",
        "data_type": "Cardholder Data",
        "implementation_status": "Implemented",
        "evidence_required": "TLS config, SSL scan results",
        "evidence_available": "Yes",
        "evidence_source": "SSL Scanner / WAF Logs",
        "evidence_link": "https://internal.example.com/tls-scan",
        "last_reviewed_date": "2025-12-10",
        "next_review_date": "2026-06-10",
        "assessor_notes": "TLS 1.3 enforced. TLS 1.0/1.1 disabled.",
    },
    # CIS Controls
    {
        "control_id": "CIS-1.1",
        "framework": "CIS Controls",
        "control_family": "Configuration Management",
        "control_title": "Asset Inventory – Enterprise Assets",
        "control_description": "Maintain an accurate inventory of all enterprise assets with the potential to store or process data.",
        "requirement_summary": "Automated asset discovery tool with inventory maintained and reviewed monthly.",
        "control_owner": "Bob Martinez",
        "system_application": "Internal Admin Console",
        "data_type": "Internal Confidential",
        "implementation_status": "Partially Implemented",
        "evidence_required": "Asset inventory report, discovery tool config",
        "evidence_available": "Partial",
        "evidence_source": "CMDB",
        "evidence_link": "https://internal.example.com/cmdb",
        "last_reviewed_date": "2025-10-01",
        "next_review_date": "2026-01-01",
        "assessor_notes": "Cloud assets not yet included in CMDB scope.",
    },
    {
        "control_id": "CIS-5.4",
        "framework": "CIS Controls",
        "control_family": "Access Control",
        "control_title": "Restrict Administrator Privileges",
        "control_description": "Use privileged access workstations for all administrative tasks, and minimize administrative account usage.",
        "requirement_summary": "Admin accounts used only for privileged tasks; no email/web on admin workstations.",
        "control_owner": "Alice Johnson",
        "system_application": "Internal Admin Console",
        "data_type": "Internal Confidential",
        "implementation_status": "Not Implemented",
        "evidence_required": "PAW policy, admin account audit",
        "evidence_available": "No",
        "evidence_source": "",
        "evidence_link": "",
        "last_reviewed_date": "2025-07-01",
        "next_review_date": "2025-10-01",
        "assessor_notes": "No PAW policy in place. Admin accounts used for general browsing.",
    },
    {
        "control_id": "CIS-6.2",
        "framework": "CIS Controls",
        "control_family": "Audit and Logging",
        "control_title": "Activate Audit Logging",
        "control_description": "Ensure audit logging is enabled on all enterprise assets.",
        "requirement_summary": "Audit logging enabled across all servers, cloud services, and critical applications.",
        "control_owner": "Carlos Lee",
        "system_application": "Healthcare Records Service",
        "data_type": "PHI",
        "implementation_status": "Implemented",
        "evidence_required": "Logging config, sample log output",
        "evidence_available": "Yes",
        "evidence_source": "CloudWatch / SIEM",
        "evidence_link": "https://internal.example.com/logging/config",
        "last_reviewed_date": "2025-11-05",
        "next_review_date": "2026-05-05",
        "assessor_notes": "CloudTrail and CloudWatch Logs enabled. Forwarding to SIEM confirmed.",
    },
    # ISO 27001
    {
        "control_id": "ISO-A.9.1",
        "framework": "ISO 27001",
        "control_family": "Access Control",
        "control_title": "Access Control Policy",
        "control_description": "An access control policy shall be established, documented, and reviewed based on business and information security requirements.",
        "requirement_summary": "Access control policy reviewed and approved at least annually.",
        "control_owner": "Alice Johnson",
        "system_application": "Customer Identity Portal",
        "data_type": "PII",
        "implementation_status": "Implemented",
        "evidence_required": "Signed policy document",
        "evidence_available": "Yes",
        "evidence_source": "Policy Repository",
        "evidence_link": "https://internal.example.com/policies/ISO-AC",
        "last_reviewed_date": "2025-10-15",
        "next_review_date": "2026-10-15",
        "assessor_notes": "Current ISO 27001 recertification cycle.",
    },
    {
        "control_id": "ISO-A.12.1",
        "framework": "ISO 27001",
        "control_family": "Change Management",
        "control_title": "Operational Procedures and Responsibilities",
        "control_description": "Operating procedures shall be documented and made available to all users who need them.",
        "requirement_summary": "Change management procedures documented; CAB reviews required for production changes.",
        "control_owner": "Evan Park",
        "system_application": "Payment Processing API",
        "data_type": "Cardholder Data",
        "implementation_status": "Implemented",
        "evidence_required": "Change management procedure, recent CAB meeting minutes",
        "evidence_available": "Yes",
        "evidence_source": "Ticketing System",
        "evidence_link": "https://internal.example.com/change-mgmt",
        "last_reviewed_date": "2025-11-10",
        "next_review_date": "2026-05-10",
        "assessor_notes": "CAB process in place. Sample tickets reviewed.",
    },
    {
        "control_id": "ISO-A.16.1",
        "framework": "ISO 27001",
        "control_family": "Incident Response",
        "control_title": "Incident Management Procedures",
        "control_description": "Responsibilities and procedures shall be established to ensure a quick, effective, and orderly response to information security incidents.",
        "requirement_summary": "Documented IR plan; tabletop exercise conducted annually.",
        "control_owner": "Fiona Walsh",
        "system_application": "Security Logging Pipeline",
        "data_type": "Security Event Logs",
        "implementation_status": "Partially Implemented",
        "evidence_required": "IR plan, tabletop exercise record",
        "evidence_available": "Partial",
        "evidence_source": "IR Team SharePoint",
        "evidence_link": "https://internal.example.com/ir-plan",
        "last_reviewed_date": "2025-06-01",
        "next_review_date": "2025-12-01",
        "assessor_notes": "IR plan exists but last tabletop exercise was 18 months ago.",
    },
    # SOC 2
    {
        "control_id": "SOC2-CC6.1",
        "framework": "SOC 2",
        "control_family": "Access Control",
        "control_title": "Logical and Physical Access Controls",
        "control_description": "The entity implements logical access security measures to protect against threats from sources outside its system boundaries.",
        "requirement_summary": "MFA enforced for all user and admin access to production systems.",
        "control_owner": "Alice Johnson",
        "system_application": "Customer Identity Portal",
        "data_type": "PII",
        "implementation_status": "Implemented",
        "evidence_required": "MFA enrollment screenshot, IAM policy",
        "evidence_available": "Yes",
        "evidence_source": "Okta Admin Console",
        "evidence_link": "https://internal.example.com/okta/mfa",
        "last_reviewed_date": "2025-12-01",
        "next_review_date": "2026-06-01",
        "assessor_notes": "MFA enforced. Coverage 98% of active users.",
    },
    {
        "control_id": "SOC2-CC7.2",
        "framework": "SOC 2",
        "control_family": "Vulnerability Management",
        "control_title": "System Monitoring",
        "control_description": "The entity monitors system components and the operation of those controls on an ongoing basis to detect anomalies.",
        "requirement_summary": "Vulnerability scans run weekly; critical findings remediated within 15 days.",
        "control_owner": "Carlos Lee",
        "system_application": "Security Logging Pipeline",
        "data_type": "Security Event Logs",
        "implementation_status": "Partially Implemented",
        "evidence_required": "Scan schedule, recent scan report, remediation tickets",
        "evidence_available": "Partial",
        "evidence_source": "Vulnerability Scanner",
        "evidence_link": "https://internal.example.com/vuln-scans",
        "last_reviewed_date": "2025-10-01",
        "next_review_date": "2026-01-01",
        "assessor_notes": "Scans run but no documented SLA for remediation timelines.",
    },
    # HIPAA
    {
        "control_id": "HIPAA-164.312a",
        "framework": "HIPAA",
        "control_family": "Access Control",
        "control_title": "Unique User Identification",
        "control_description": "Assign a unique name or number for identifying and tracking user identity in systems handling ePHI.",
        "requirement_summary": "No shared accounts on systems that store or process ePHI.",
        "control_owner": "Alice Johnson",
        "system_application": "Healthcare Records Service",
        "data_type": "PHI",
        "implementation_status": "Implemented",
        "evidence_required": "User account audit, no shared account confirmation",
        "evidence_available": "Yes",
        "evidence_source": "Active Directory Report",
        "evidence_link": "https://internal.example.com/ad/reports",
        "last_reviewed_date": "2025-11-15",
        "next_review_date": "2026-05-15",
        "assessor_notes": "All ePHI system accounts are individual. Last audit Nov 2025.",
    },
    {
        "control_id": "HIPAA-164.312e",
        "framework": "HIPAA",
        "control_family": "Encryption and Data Protection",
        "control_title": "Transmission Security",
        "control_description": "Implement technical security measures to guard against unauthorized access to ePHI transmitted over electronic communications networks.",
        "requirement_summary": "All ePHI in transit encrypted with TLS 1.2 or higher.",
        "control_owner": "Diana Chen",
        "system_application": "Healthcare Records Service",
        "data_type": "PHI",
        "implementation_status": "Implemented",
        "evidence_required": "TLS configuration, network diagram",
        "evidence_available": "Yes",
        "evidence_source": "Network Team",
        "evidence_link": "https://internal.example.com/network/tls",
        "last_reviewed_date": "2025-12-05",
        "next_review_date": "2026-06-05",
        "assessor_notes": "TLS 1.3 deployed. TLS 1.1 disabled.",
    },
    {
        "control_id": "HIPAA-164.308a",
        "framework": "HIPAA",
        "control_family": "Risk Assessment",
        "control_title": "Risk Analysis",
        "control_description": "Conduct an accurate and thorough assessment of potential risks and vulnerabilities to ePHI.",
        "requirement_summary": "Annual risk assessment documented and approved by executive.",
        "control_owner": "Gina Torres",
        "system_application": "Healthcare Records Service",
        "data_type": "PHI",
        "implementation_status": "Partially Implemented",
        "evidence_required": "Risk assessment report, executive sign-off",
        "evidence_available": "Partial",
        "evidence_source": "GRC Team",
        "evidence_link": "",
        "last_reviewed_date": "2024-12-01",
        "next_review_date": "2025-12-01",
        "assessor_notes": "Last full risk assessment was Dec 2024. Update overdue.",
    },
    # PCI DSS
    {
        "control_id": "PCI-6.4",
        "framework": "PCI DSS",
        "control_family": "Vulnerability Management",
        "control_title": "Protect Public-Facing Web Applications",
        "control_description": "Address new threats and vulnerabilities for public-facing web applications and ensure these applications are protected from known attacks.",
        "requirement_summary": "WAF deployed; annual penetration test; code review for new releases.",
        "control_owner": "Evan Park",
        "system_application": "Payment Processing API",
        "data_type": "Cardholder Data",
        "implementation_status": "Implemented",
        "evidence_required": "WAF config, pentest report, code review records",
        "evidence_available": "Yes",
        "evidence_source": "Security Team",
        "evidence_link": "https://internal.example.com/pentest/2025",
        "last_reviewed_date": "2025-10-20",
        "next_review_date": "2026-10-20",
        "assessor_notes": "Annual pentest completed Oct 2025. WAF active.",
    },
    {
        "control_id": "PCI-8.3",
        "framework": "PCI DSS",
        "control_family": "Access Control",
        "control_title": "MFA for Non-Console Administrative Access",
        "control_description": "All non-console access into the cardholder data environment requires multi-factor authentication.",
        "requirement_summary": "MFA enforced on all remote/admin access to CDE systems.",
        "control_owner": "Alice Johnson",
        "system_application": "Payment Processing API",
        "data_type": "Cardholder Data",
        "implementation_status": "Implemented",
        "evidence_required": "MFA policy, admin login screenshot",
        "evidence_available": "Yes",
        "evidence_source": "Okta / PCI QSA Report",
        "evidence_link": "https://internal.example.com/pci/mfa",
        "last_reviewed_date": "2025-11-01",
        "next_review_date": "2026-11-01",
        "assessor_notes": "MFA confirmed via QSA walkthrough.",
    },
    {
        "control_id": "PCI-10.2",
        "framework": "PCI DSS",
        "control_family": "Audit and Logging",
        "control_title": "Implement Audit Logs",
        "control_description": "Implement audit logs to capture all specified events in the CDE.",
        "requirement_summary": "Log all user access, admin actions, and data access in CDE. Retain 12 months.",
        "control_owner": "Carlos Lee",
        "system_application": "Payment Processing API",
        "data_type": "Cardholder Data",
        "implementation_status": "Implemented",
        "evidence_required": "Log config, 12-month retention policy, sample log",
        "evidence_available": "Yes",
        "evidence_source": "SIEM / CloudWatch",
        "evidence_link": "https://internal.example.com/pci/logs",
        "last_reviewed_date": "2025-11-15",
        "next_review_date": "2026-05-15",
        "assessor_notes": "Logs retained 13 months. Confirmed by QSA.",
    },
    # HITRUST
    {
        "control_id": "HITRUST-01.a",
        "framework": "HITRUST",
        "control_family": "Access Control",
        "control_title": "Access Control Policy",
        "control_description": "The organization establishes access control requirements based on business and security needs.",
        "requirement_summary": "Documented access control policy aligned to HITRUST CSF requirements.",
        "control_owner": "Alice Johnson",
        "system_application": "Healthcare Records Service",
        "data_type": "PHI",
        "implementation_status": "Implemented",
        "evidence_required": "HITRUST-aligned AC policy",
        "evidence_available": "Yes",
        "evidence_source": "Policy Repository",
        "evidence_link": "https://internal.example.com/policies/HITRUST-AC",
        "last_reviewed_date": "2025-09-01",
        "next_review_date": "2026-09-01",
        "assessor_notes": "HITRUST readiness assessment completed.",
    },
    {
        "control_id": "HITRUST-09.ab",
        "framework": "HITRUST",
        "control_family": "Vendor Risk",
        "control_title": "Third-Party Information Security",
        "control_description": "Formal agreements are in place with third parties that handle sensitive information, covering security requirements.",
        "requirement_summary": "BAAs signed with all vendors handling PHI; annual vendor risk reviews.",
        "control_owner": "Gina Torres",
        "system_application": "Vendor Risk Platform",
        "data_type": "PHI",
        "implementation_status": "Partially Implemented",
        "evidence_required": "BAA inventory, vendor risk assessments",
        "evidence_available": "Partial",
        "evidence_source": "Legal / Vendor Risk Team",
        "evidence_link": "https://internal.example.com/vendor-risk",
        "last_reviewed_date": "2025-08-01",
        "next_review_date": "2025-11-01",
        "assessor_notes": "3 of 8 PHI vendors missing current BAA. Annual reviews not completed.",
    },
    {
        "control_id": "HITRUST-06.d",
        "framework": "HITRUST",
        "control_family": "Security Awareness",
        "control_title": "Information Security Awareness and Training",
        "control_description": "All workforce members receive appropriate security awareness training.",
        "requirement_summary": "Annual security awareness training with completion tracking; phishing simulation quarterly.",
        "control_owner": "Hana Kim",
        "system_application": "Healthcare Records Service",
        "data_type": "PHI",
        "implementation_status": "Implemented",
        "evidence_required": "Training completion report, phishing sim results",
        "evidence_available": "Yes",
        "evidence_source": "LMS / HR System",
        "evidence_link": "https://internal.example.com/training/completion",
        "last_reviewed_date": "2025-12-15",
        "next_review_date": "2026-12-15",
        "assessor_notes": "98% completion rate. Q4 phishing sim completed.",
    },
    # Additional Controls for variety
    {
        "control_id": "NIST-IR-4",
        "framework": "NIST SP 800-53",
        "control_family": "Incident Response",
        "control_title": "Incident Handling",
        "control_description": "Organization implements an incident handling capability for security incidents including preparation, detection, analysis, containment, eradication, and recovery.",
        "requirement_summary": "Documented IR runbooks; incidents tracked in ticketing system; post-incident review.",
        "control_owner": "Fiona Walsh",
        "system_application": "Security Logging Pipeline",
        "data_type": "Security Event Logs",
        "implementation_status": "Partially Implemented",
        "evidence_required": "IR runbooks, incident ticket samples, post-incident reports",
        "evidence_available": "Partial",
        "evidence_source": "IR Team / Ticketing System",
        "evidence_link": "https://internal.example.com/incidents",
        "last_reviewed_date": "2025-07-01",
        "next_review_date": "2025-10-01",
        "assessor_notes": "Runbooks exist but post-incident review process not consistently followed.",
    },
    {
        "control_id": "NIST-RA-5",
        "framework": "NIST SP 800-53",
        "control_family": "Vulnerability Management",
        "control_title": "Vulnerability Monitoring and Scanning",
        "control_description": "Organization scans for vulnerabilities in the information system and hosted applications at defined frequencies.",
        "requirement_summary": "Weekly authenticated scans; critical CVE remediation within 15 days.",
        "control_owner": "Carlos Lee",
        "system_application": "AWS S3 Data Lake",
        "data_type": "PHI",
        "implementation_status": "Not Implemented",
        "evidence_required": "Scan schedule, recent report, remediation records",
        "evidence_available": "No",
        "evidence_source": "",
        "evidence_link": "",
        "last_reviewed_date": "2025-06-01",
        "next_review_date": "2025-09-01",
        "assessor_notes": "No vulnerability scanning coverage on S3 workloads. Gap identified.",
    },
    {
        "control_id": "CIS-12.1",
        "framework": "CIS Controls",
        "control_family": "Vendor Risk",
        "control_title": "Network Infrastructure Management",
        "control_description": "Establish and maintain a comprehensive network infrastructure management process to ensure network devices are securely managed.",
        "requirement_summary": "Network device inventory maintained; firmware updated within 30 days of release.",
        "control_owner": "Bob Martinez",
        "system_application": "Vendor Risk Platform",
        "data_type": "Internal Confidential",
        "implementation_status": "Not Assessed",
        "evidence_required": "Network device inventory, firmware update records",
        "evidence_available": "No",
        "evidence_source": "",
        "evidence_link": "",
        "last_reviewed_date": "",
        "next_review_date": "2026-01-15",
        "assessor_notes": "Assessment not yet performed for vendor network segments.",
    },
    {
        "control_id": "NIST-CM-6",
        "framework": "NIST SP 800-53",
        "control_family": "Configuration Management",
        "control_title": "Configuration Settings",
        "control_description": "Organization establishes and documents configuration settings for information technology products employed within the information system.",
        "requirement_summary": "CIS Benchmarks applied; configuration compliance scanned monthly.",
        "control_owner": "Bob Martinez",
        "system_application": "AWS S3 Data Lake",
        "data_type": "PHI",
        "implementation_status": "Partially Implemented",
        "evidence_required": "Baseline config docs, compliance scan results",
        "evidence_available": "Partial",
        "evidence_source": "AWS Config / Security Hub",
        "evidence_link": "https://internal.example.com/aws/config",
        "last_reviewed_date": "2025-10-01",
        "next_review_date": "2026-01-01",
        "assessor_notes": "AWS Config enabled but drift alerts not remediated within SLA.",
    },
    {
        "control_id": "SOC2-CC9.2",
        "framework": "SOC 2",
        "control_family": "Vendor Risk",
        "control_title": "Vendor Risk Management",
        "control_description": "The entity assesses and manages risks associated with vendors and business partners.",
        "requirement_summary": "Annual vendor risk assessments for critical vendors; SOC 2 reports obtained.",
        "control_owner": "Gina Torres",
        "system_application": "Vendor Risk Platform",
        "data_type": "Internal Confidential",
        "implementation_status": "Partially Implemented",
        "evidence_required": "Vendor risk register, SOC 2 reports, assessment records",
        "evidence_available": "Partial",
        "evidence_source": "Vendor Risk Platform",
        "evidence_link": "https://internal.example.com/vendor-risk/assessments",
        "last_reviewed_date": "2025-08-15",
        "next_review_date": "2025-11-15",
        "assessor_notes": "2 critical vendors missing annual assessment. SOC 2 reports obtained for 4 of 6.",
    },
]

# ---------------------------------------------------------------------------
# Evidence  (20 rows)
# ---------------------------------------------------------------------------
EVIDENCE = [
    {
        "evidence_id": "EV-001",
        "related_control_id": "NIST-AC-1",
        "evidence_name": "Access Control Policy v3.2",
        "evidence_type": "Policy",
        "evidence_description": "Organization-wide access control policy document approved by CISO.",
        "evidence_owner": "Alice Johnson",
        "evidence_source": "Policy Repository",
        "collection_method": "Document download",
        "evidence_status": "Available",
        "date_collected": "2025-11-01",
        "expiration_date": "2026-11-01",
        "review_notes": "Current; next review Nov 2026.",
    },
    {
        "evidence_id": "EV-002",
        "related_control_id": "NIST-AC-2",
        "evidence_name": "Q3 2025 Access Review Report",
        "evidence_type": "Access Review",
        "evidence_description": "Quarterly access review for Customer Identity Portal users and admins.",
        "evidence_owner": "Alice Johnson",
        "evidence_source": "IAM System",
        "collection_method": "Export from IAM dashboard",
        "evidence_status": "Outdated",
        "date_collected": "2025-09-15",
        "expiration_date": "2025-12-15",
        "review_notes": "Q4 review overdue. De-provisioning records incomplete.",
    },
    {
        "evidence_id": "EV-003",
        "related_control_id": "NIST-AC-3",
        "evidence_name": "RBAC Configuration Export",
        "evidence_type": "Configuration Export",
        "evidence_description": "Export of role assignments on Internal Admin Console.",
        "evidence_owner": "Bob Martinez",
        "evidence_source": "Admin Console",
        "collection_method": "Manual export",
        "evidence_status": "Missing",
        "date_collected": "",
        "expiration_date": "",
        "review_notes": "Not collected. Shared admin account discovered during walkthrough.",
    },
    {
        "evidence_id": "EV-004",
        "related_control_id": "NIST-AU-2",
        "evidence_name": "SIEM Audit Rule Configuration",
        "evidence_type": "SIEM Alert",
        "evidence_description": "Screenshot of SIEM rule set showing defined audit events.",
        "evidence_owner": "Carlos Lee",
        "evidence_source": "SIEM Platform",
        "collection_method": "Screenshot",
        "evidence_status": "Available",
        "date_collected": "2025-10-15",
        "expiration_date": "2026-04-15",
        "review_notes": "Rules reviewed and approved by Security team.",
    },
    {
        "evidence_id": "EV-005",
        "related_control_id": "NIST-AU-6",
        "evidence_name": "Weekly Log Review Records",
        "evidence_type": "Log Sample",
        "evidence_description": "Records of weekly log review sessions and findings.",
        "evidence_owner": "Carlos Lee",
        "evidence_source": "SIEM Platform",
        "collection_method": "Manual documentation",
        "evidence_status": "Incomplete",
        "date_collected": "2025-09-01",
        "expiration_date": "2025-12-01",
        "review_notes": "Only 4 of 12 weekly reviews documented. Process not formalized.",
    },
    {
        "evidence_id": "EV-006",
        "related_control_id": "NIST-SC-28",
        "evidence_name": "S3 Encryption Configuration",
        "evidence_type": "Cloud Configuration",
        "evidence_description": "AWS Console screenshot and Config rule confirming S3 SSE-KMS encryption.",
        "evidence_owner": "Diana Chen",
        "evidence_source": "AWS Console",
        "collection_method": "Screenshot + Config export",
        "evidence_status": "Available",
        "date_collected": "2025-11-20",
        "expiration_date": "2026-05-20",
        "review_notes": "KMS key rotation enabled. Confirmed by AWS Config rule.",
    },
    {
        "evidence_id": "EV-007",
        "related_control_id": "NIST-SC-8",
        "evidence_name": "TLS 1.3 SSL Scan Results",
        "evidence_type": "Vulnerability Scan",
        "evidence_description": "SSL/TLS scan output confirming TLS 1.3 and disabling of legacy protocols.",
        "evidence_owner": "Diana Chen",
        "evidence_source": "SSL Scanner",
        "collection_method": "Automated scan",
        "evidence_status": "Available",
        "date_collected": "2025-12-10",
        "expiration_date": "2026-06-10",
        "review_notes": "TLS 1.0 and 1.1 confirmed disabled.",
    },
    {
        "evidence_id": "EV-008",
        "related_control_id": "CIS-5.4",
        "evidence_name": "Privileged Access Workstation Policy",
        "evidence_type": "Policy",
        "evidence_description": "PAW policy document covering admin account usage restrictions.",
        "evidence_owner": "Alice Johnson",
        "evidence_source": "Policy Repository",
        "collection_method": "Document download",
        "evidence_status": "Missing",
        "date_collected": "",
        "expiration_date": "",
        "review_notes": "No PAW policy exists. Finding raised.",
    },
    {
        "evidence_id": "EV-009",
        "related_control_id": "ISO-A.16.1",
        "evidence_name": "IR Tabletop Exercise Record – 2024",
        "evidence_type": "Procedure",
        "evidence_description": "Documentation of annual incident response tabletop exercise.",
        "evidence_owner": "Fiona Walsh",
        "evidence_source": "IR Team SharePoint",
        "collection_method": "Document review",
        "evidence_status": "Outdated",
        "date_collected": "2024-06-01",
        "expiration_date": "2025-06-01",
        "review_notes": "Exercise was 18 months ago. 2025 exercise not yet completed.",
    },
    {
        "evidence_id": "EV-010",
        "related_control_id": "SOC2-CC6.1",
        "evidence_name": "Okta MFA Enrollment Report",
        "evidence_type": "Screenshot",
        "evidence_description": "Okta admin console export showing MFA enrollment status for all users.",
        "evidence_owner": "Alice Johnson",
        "evidence_source": "Okta Admin Console",
        "collection_method": "Dashboard export",
        "evidence_status": "Available",
        "date_collected": "2025-12-01",
        "expiration_date": "2026-06-01",
        "review_notes": "98% enrollment rate. 5 users pending enrollment.",
    },
    {
        "evidence_id": "EV-011",
        "related_control_id": "SOC2-CC7.2",
        "evidence_name": "Weekly Vulnerability Scan Report",
        "evidence_type": "Vulnerability Scan",
        "evidence_description": "Most recent vulnerability scan results from Qualys.",
        "evidence_owner": "Carlos Lee",
        "evidence_source": "Qualys",
        "collection_method": "Automated scan export",
        "evidence_status": "Incomplete",
        "date_collected": "2025-10-01",
        "expiration_date": "2026-01-01",
        "review_notes": "Scan results available but no documented remediation SLA policy.",
    },
    {
        "evidence_id": "EV-012",
        "related_control_id": "HIPAA-164.312a",
        "evidence_name": "Active Directory User Account Audit",
        "evidence_type": "Access Review",
        "evidence_description": "AD export confirming no shared accounts on ePHI systems.",
        "evidence_owner": "Alice Johnson",
        "evidence_source": "Active Directory",
        "collection_method": "PowerShell script export",
        "evidence_status": "Available",
        "date_collected": "2025-11-15",
        "expiration_date": "2026-05-15",
        "review_notes": "All accounts confirmed individual. No shared accounts found.",
    },
    {
        "evidence_id": "EV-013",
        "related_control_id": "HIPAA-164.308a",
        "evidence_name": "Annual Risk Assessment 2024",
        "evidence_type": "Vendor Report",
        "evidence_description": "Formal HIPAA risk analysis document with executive sign-off.",
        "evidence_owner": "Gina Torres",
        "evidence_source": "GRC Team",
        "collection_method": "Document review",
        "evidence_status": "Outdated",
        "date_collected": "2024-12-01",
        "expiration_date": "2025-12-01",
        "review_notes": "2024 assessment expired. 2025 update not yet completed.",
    },
    {
        "evidence_id": "EV-014",
        "related_control_id": "PCI-6.4",
        "evidence_name": "Annual Penetration Test Report 2025",
        "evidence_type": "Vendor Report",
        "evidence_description": "Third-party penetration test report for Payment Processing API.",
        "evidence_owner": "Evan Park",
        "evidence_source": "Security Vendor",
        "collection_method": "Report from vendor",
        "evidence_status": "Available",
        "date_collected": "2025-10-20",
        "expiration_date": "2026-10-20",
        "review_notes": "Pentest completed. All critical findings remediated.",
    },
    {
        "evidence_id": "EV-015",
        "related_control_id": "HITRUST-09.ab",
        "evidence_name": "Business Associate Agreement Register",
        "evidence_type": "Policy",
        "evidence_description": "Inventory of BAAs with all PHI-handling vendors.",
        "evidence_owner": "Gina Torres",
        "evidence_source": "Legal Team",
        "collection_method": "Spreadsheet review",
        "evidence_status": "Incomplete",
        "date_collected": "2025-08-01",
        "expiration_date": "2025-11-01",
        "review_notes": "3 of 8 BAAs missing or expired. Vendor risk gap.",
    },
    {
        "evidence_id": "EV-016",
        "related_control_id": "HITRUST-06.d",
        "evidence_name": "Security Awareness Training Completion Report",
        "evidence_type": "Screenshot",
        "evidence_description": "LMS report showing 98% completion rate for annual security training.",
        "evidence_owner": "Hana Kim",
        "evidence_source": "LMS",
        "collection_method": "LMS report export",
        "evidence_status": "Available",
        "date_collected": "2025-12-15",
        "expiration_date": "2026-12-15",
        "review_notes": "98% completion. Outstanding 2% tracked via HR.",
    },
    {
        "evidence_id": "EV-017",
        "related_control_id": "NIST-RA-5",
        "evidence_name": "AWS S3 Vulnerability Scan Coverage",
        "evidence_type": "Vulnerability Scan",
        "evidence_description": "Evidence confirming vulnerability scan coverage of AWS S3 workloads.",
        "evidence_owner": "Carlos Lee",
        "evidence_source": "Vulnerability Scanner",
        "collection_method": "Scanner agent config",
        "evidence_status": "Missing",
        "date_collected": "",
        "expiration_date": "",
        "review_notes": "No scanner coverage for S3 workloads. Critical gap.",
    },
    {
        "evidence_id": "EV-018",
        "related_control_id": "NIST-CM-6",
        "evidence_name": "AWS Config Compliance Report",
        "evidence_type": "Cloud Configuration",
        "evidence_description": "AWS Config and Security Hub compliance dashboard showing configuration drift.",
        "evidence_owner": "Bob Martinez",
        "evidence_source": "AWS Security Hub",
        "collection_method": "Console export",
        "evidence_status": "Incomplete",
        "date_collected": "2025-10-01",
        "expiration_date": "2026-01-01",
        "review_notes": "Config enabled but 14 drift findings unresolved past 30-day SLA.",
    },
    {
        "evidence_id": "EV-019",
        "related_control_id": "SOC2-CC9.2",
        "evidence_name": "Vendor Risk Assessment Records 2025",
        "evidence_type": "Vendor Report",
        "evidence_description": "Annual vendor risk assessment records for critical vendors.",
        "evidence_owner": "Gina Torres",
        "evidence_source": "Vendor Risk Platform",
        "collection_method": "Platform export",
        "evidence_status": "Incomplete",
        "date_collected": "2025-08-15",
        "expiration_date": "2025-11-15",
        "review_notes": "2 critical vendors not yet assessed for 2025.",
    },
    {
        "evidence_id": "EV-020",
        "related_control_id": "CIS-1.1",
        "evidence_name": "CMDB Asset Inventory Report",
        "evidence_type": "Configuration Export",
        "evidence_description": "CMDB export showing enterprise asset inventory.",
        "evidence_owner": "Bob Martinez",
        "evidence_source": "CMDB",
        "collection_method": "System export",
        "evidence_status": "Incomplete",
        "date_collected": "2025-10-01",
        "expiration_date": "2026-01-01",
        "review_notes": "Cloud assets not in scope of CMDB. Partial coverage only.",
    },
]

# ---------------------------------------------------------------------------
# Findings  (10 rows)
# ---------------------------------------------------------------------------
FINDINGS = [
    {
        "finding_id": "FND-001",
        "related_control_id": "NIST-AC-3",
        "finding_title": "Shared Admin Account on Internal Admin Console",
        "finding_description": "A shared administrative account is being used by multiple IT staff on the Internal Admin Console, violating access enforcement and unique identification requirements.",
        "risk_theme": "Excessive Access",
        "severity": "High",
        "likelihood": 4,
        "impact": 4,
        "inherent_risk": "High",
        "existing_controls": "Password rotation policy exists; manual log review in place.",
        "residual_risk": "Medium",
        "business_impact": "Inability to attribute administrative actions to specific individuals; audit trail compromise.",
        "compliance_impact": "NIST AC-3, HIPAA 164.312a, SOC 2 CC6.1 non-compliance.",
        "recommended_action": "Disable shared account; provision individual admin accounts with MFA; implement PAM solution.",
        "finding_owner": "Bob Martinez",
        "due_date": "2026-02-28",
        "status": "In Progress",
        "closure_evidence": "",
        "closure_notes": "",
    },
    {
        "finding_id": "FND-002",
        "related_control_id": "CIS-5.4",
        "finding_title": "No Privileged Access Workstation Policy",
        "finding_description": "No documented policy exists for privileged access workstations. Admin accounts are used for general browsing and email, increasing risk of credential compromise.",
        "risk_theme": "Poor Configuration",
        "severity": "High",
        "likelihood": 3,
        "impact": 4,
        "inherent_risk": "High",
        "existing_controls": "Antivirus deployed on endpoints.",
        "residual_risk": "High",
        "business_impact": "Admin credential exposure through phishing or malware could lead to full system compromise.",
        "compliance_impact": "CIS Controls 5.4 gap; PCI DSS requirement for admin access controls.",
        "recommended_action": "Develop PAW policy; separate admin and standard user accounts; consider PAM tooling.",
        "finding_owner": "Alice Johnson",
        "due_date": "2026-03-31",
        "status": "Open",
        "closure_evidence": "",
        "closure_notes": "",
    },
    {
        "finding_id": "FND-003",
        "related_control_id": "ISO-A.16.1",
        "finding_title": "IR Tabletop Exercise Not Conducted in 18 Months",
        "finding_description": "The organization has not conducted an incident response tabletop exercise within the required annual timeframe. The last exercise was 18 months ago.",
        "risk_theme": "Missing Review Process",
        "severity": "Medium",
        "likelihood": 3,
        "impact": 3,
        "inherent_risk": "Medium",
        "existing_controls": "IR plan document exists; dedicated IR team in place.",
        "residual_risk": "Medium",
        "business_impact": "Unprepared response to real incidents; prolonged recovery time.",
        "compliance_impact": "ISO 27001 A.16.1, HITRUST IR requirement gap.",
        "recommended_action": "Schedule and conduct tabletop exercise within 60 days; update IR plan based on outcomes.",
        "finding_owner": "Fiona Walsh",
        "due_date": "2026-01-31",
        "status": "In Progress",
        "closure_evidence": "",
        "closure_notes": "",
    },
    {
        "finding_id": "FND-004",
        "related_control_id": "NIST-RA-5",
        "finding_title": "No Vulnerability Scan Coverage for AWS S3 Data Lake",
        "finding_description": "The AWS S3 Data Lake containing PHI has no vulnerability scanning coverage. No scanner agents or cloud-native scanning is configured for this workload.",
        "risk_theme": "Unpatched System",
        "severity": "Critical",
        "likelihood": 4,
        "impact": 5,
        "inherent_risk": "Critical",
        "existing_controls": "S3 encryption at rest is enabled; bucket policies restrict public access.",
        "residual_risk": "High",
        "business_impact": "Undetected vulnerabilities in PHI-processing workloads could lead to data breach and regulatory penalties.",
        "compliance_impact": "NIST RA-5, HIPAA 164.308a, HITRUST critical vulnerability scanning requirement.",
        "recommended_action": "Deploy AWS Inspector or equivalent; configure weekly scan schedule; integrate with SIEM alerting.",
        "finding_owner": "Carlos Lee",
        "due_date": "2026-01-15",
        "status": "Open",
        "closure_evidence": "",
        "closure_notes": "",
    },
    {
        "finding_id": "FND-005",
        "related_control_id": "HIPAA-164.308a",
        "finding_title": "Annual HIPAA Risk Assessment Overdue",
        "finding_description": "The annual HIPAA risk analysis has not been updated for the current year. The last approved assessment was from December 2024 and is now expired.",
        "risk_theme": "Missing Review Process",
        "severity": "High",
        "likelihood": 3,
        "impact": 4,
        "inherent_risk": "High",
        "existing_controls": "Previous risk assessment on file; GRC team has process knowledge.",
        "residual_risk": "Medium",
        "business_impact": "Regulatory violation risk; failure to identify new risks to ePHI.",
        "compliance_impact": "HIPAA Security Rule 164.308(a)(1) direct requirement.",
        "recommended_action": "Initiate 2025 risk assessment within 30 days; obtain executive approval; document and distribute.",
        "finding_owner": "Gina Torres",
        "due_date": "2026-02-15",
        "status": "In Progress",
        "closure_evidence": "",
        "closure_notes": "",
    },
    {
        "finding_id": "FND-006",
        "related_control_id": "NIST-AU-6",
        "finding_title": "Log Review Process Not Formally Documented",
        "finding_description": "While SIEM alert rules exist, the weekly log review process is not documented as a formal procedure. Only 4 of 12 recent review sessions were recorded.",
        "risk_theme": "Weak Logging",
        "severity": "Medium",
        "likelihood": 3,
        "impact": 3,
        "inherent_risk": "Medium",
        "existing_controls": "SIEM alert rules active; security team performs informal reviews.",
        "residual_risk": "Low",
        "business_impact": "Audit evidence gap; inability to demonstrate control effectiveness.",
        "compliance_impact": "NIST AU-6, SOC 2 CC7.2, PCI DSS 10.2 audit log review requirement.",
        "recommended_action": "Document log review SOP; assign DRI; implement tracking in ticketing system.",
        "finding_owner": "Carlos Lee",
        "due_date": "2026-01-31",
        "status": "In Progress",
        "closure_evidence": "",
        "closure_notes": "",
    },
    {
        "finding_id": "FND-007",
        "related_control_id": "HITRUST-09.ab",
        "finding_title": "3 PHI Vendors Missing Business Associate Agreements",
        "finding_description": "Three vendors that handle protected health information do not have current, executed Business Associate Agreements on file. Two BAAs are expired.",
        "risk_theme": "Vendor Risk",
        "severity": "High",
        "likelihood": 3,
        "impact": 5,
        "inherent_risk": "Critical",
        "existing_controls": "Vendor contracts include general data protection language.",
        "residual_risk": "High",
        "business_impact": "Legal and regulatory exposure under HIPAA. Potential OCR audit finding.",
        "compliance_impact": "HIPAA 164.314, HITRUST 09.ab direct BAA requirement.",
        "recommended_action": "Obtain executed BAAs from all 3 vendors within 45 days; renew expired BAAs; update vendor inventory.",
        "finding_owner": "Gina Torres",
        "due_date": "2026-02-01",
        "status": "In Progress",
        "closure_evidence": "",
        "closure_notes": "",
    },
    {
        "finding_id": "FND-008",
        "related_control_id": "NIST-CM-6",
        "finding_title": "14 AWS Configuration Drift Findings Unresolved",
        "finding_description": "AWS Config and Security Hub report 14 configuration drift findings that have exceeded the 30-day SLA for remediation. Affected resources include EC2 instances and IAM policies.",
        "risk_theme": "Poor Configuration",
        "severity": "Medium",
        "likelihood": 3,
        "impact": 3,
        "inherent_risk": "Medium",
        "existing_controls": "AWS Config enabled; Security Hub findings visible to team.",
        "residual_risk": "Low",
        "business_impact": "Misconfigured resources may expose data or create privilege escalation paths.",
        "compliance_impact": "NIST CM-6, CIS Benchmark compliance, SOC 2 CC6 gap.",
        "recommended_action": "Remediate all 14 findings within 2 weeks; establish automated remediation for common drift types.",
        "finding_owner": "Bob Martinez",
        "due_date": "2026-01-20",
        "status": "In Progress",
        "closure_evidence": "",
        "closure_notes": "",
    },
    {
        "finding_id": "FND-009",
        "related_control_id": "SOC2-CC7.2",
        "finding_title": "No Documented Vulnerability Remediation SLA",
        "finding_description": "Vulnerability scans are performed but there is no documented SLA defining how quickly vulnerabilities must be remediated based on severity. Critical CVEs have remained open beyond 30 days.",
        "risk_theme": "Unpatched System",
        "severity": "Medium",
        "likelihood": 3,
        "impact": 3,
        "inherent_risk": "Medium",
        "existing_controls": "Weekly scans run; informal remediation tracking in ticketing system.",
        "residual_risk": "Low",
        "business_impact": "Prolonged exposure to exploitable vulnerabilities.",
        "compliance_impact": "SOC 2 CC7.2, PCI DSS 6.3.3 patch management requirement.",
        "recommended_action": "Define and publish vulnerability SLA policy (Critical=7d, High=15d, Med=30d); track in JIRA.",
        "finding_owner": "Carlos Lee",
        "due_date": "2026-02-28",
        "status": "Open",
        "closure_evidence": "",
        "closure_notes": "",
    },
    {
        "finding_id": "FND-010",
        "related_control_id": "NIST-AC-2",
        "finding_title": "De-Provisioning Process Not Automated – Orphaned Accounts Risk",
        "finding_description": "User de-provisioning from the Customer Identity Portal is a manual process. Review of Q3 access records shows 6 accounts belonging to terminated employees were not de-provisioned within the required 24-hour window.",
        "risk_theme": "Excessive Access",
        "severity": "High",
        "likelihood": 4,
        "impact": 4,
        "inherent_risk": "High",
        "existing_controls": "HR notifies IT upon termination via email; quarterly access reviews.",
        "residual_risk": "Medium",
        "business_impact": "Terminated employees retaining system access creates data exposure and insider threat risk.",
        "compliance_impact": "NIST AC-2, SOC 2 CC6.2, ISO 27001 A.9.2 account management requirement.",
        "recommended_action": "Automate de-provisioning via SCIM/HRMS integration; set SLA to 2 hours; add alert for failures.",
        "finding_owner": "Alice Johnson",
        "due_date": "2026-03-15",
        "status": "Open",
        "closure_evidence": "",
        "closure_notes": "",
    },
]

# ---------------------------------------------------------------------------
# Remediation  (8 rows)
# ---------------------------------------------------------------------------
REMEDIATION = [
    {
        "remediation_id": "REM-001",
        "finding_id": "FND-001",
        "owner": "Bob Martinez",
        "action_plan": "1. Identify all users of shared admin account. 2. Provision individual admin accounts. 3. Enable MFA on all admin accounts. 4. Disable shared account. 5. Deploy PAM solution for session recording.",
        "target_date": "2026-02-28",
        "current_status": "In Progress",
        "progress_notes": "Individual accounts provisioned for 4 of 7 users. PAM vendor selected.",
        "dependency": "PAM vendor contract approval",
        "validation_required": "Yes",
        "closure_evidence": "",
        "date_closed": "",
    },
    {
        "remediation_id": "REM-002",
        "finding_id": "FND-002",
        "owner": "Alice Johnson",
        "action_plan": "1. Draft Privileged Access Workstation policy. 2. Get CISO approval. 3. Procure dedicated admin workstations. 4. Configure admin-only policy (no email/browser). 5. Communicate to IT admins.",
        "target_date": "2026-03-31",
        "current_status": "Open",
        "progress_notes": "Policy draft started. Waiting for CISO calendar for review.",
        "dependency": "CISO availability for policy review",
        "validation_required": "Yes",
        "closure_evidence": "",
        "date_closed": "",
    },
    {
        "remediation_id": "REM-003",
        "finding_id": "FND-003",
        "owner": "Fiona Walsh",
        "action_plan": "1. Schedule tabletop exercise with IR team and stakeholders. 2. Prepare scenario (ransomware). 3. Conduct exercise. 4. Document lessons learned. 5. Update IR plan.",
        "target_date": "2026-01-31",
        "current_status": "In Progress",
        "progress_notes": "Exercise scheduled for Jan 20, 2026. Scenario deck in review.",
        "dependency": "Stakeholder availability",
        "validation_required": "No",
        "closure_evidence": "",
        "date_closed": "",
    },
    {
        "remediation_id": "REM-004",
        "finding_id": "FND-004",
        "owner": "Carlos Lee",
        "action_plan": "1. Enable AWS Inspector on all EC2 instances in S3 Data Lake VPC. 2. Configure ECR container scanning. 3. Integrate Inspector findings with SIEM. 4. Set up weekly report distribution. 5. Define remediation SLA.",
        "target_date": "2026-01-15",
        "current_status": "In Progress",
        "progress_notes": "AWS Inspector enabled in dev environment. Production deployment pending change request approval.",
        "dependency": "Change management approval",
        "validation_required": "Yes",
        "closure_evidence": "",
        "date_closed": "",
    },
    {
        "remediation_id": "REM-005",
        "finding_id": "FND-005",
        "owner": "Gina Torres",
        "action_plan": "1. Kick off 2025 HIPAA risk assessment. 2. Engage GRC tool or consultant. 3. Interview system owners. 4. Complete risk register. 5. Obtain CISO and executive sign-off. 6. Distribute findings.",
        "target_date": "2026-02-15",
        "current_status": "In Progress",
        "progress_notes": "System owner interviews 60% complete. Risk register draft in progress.",
        "dependency": "System owner availability",
        "validation_required": "Yes",
        "closure_evidence": "",
        "date_closed": "",
    },
    {
        "remediation_id": "REM-006",
        "finding_id": "FND-007",
        "owner": "Gina Torres",
        "action_plan": "1. Contact 3 non-compliant vendors. 2. Send BAA for signature. 3. Follow up weekly. 4. Archive executed BAAs in legal repository. 5. Update vendor inventory.",
        "target_date": "2026-02-01",
        "current_status": "In Progress",
        "progress_notes": "BAA sent to 2 of 3 vendors. Awaiting signature. Third vendor unresponsive.",
        "dependency": "Vendor response",
        "validation_required": "Yes",
        "closure_evidence": "",
        "date_closed": "",
    },
    {
        "remediation_id": "REM-007",
        "finding_id": "FND-008",
        "owner": "Bob Martinez",
        "action_plan": "1. Prioritize 14 drift findings by severity. 2. Remediate Critical/High within 7 days. 3. Remediate Medium within 14 days. 4. Document each fix. 5. Set up Config auto-remediation for recurring issues.",
        "target_date": "2026-01-20",
        "current_status": "In Progress",
        "progress_notes": "5 of 14 findings remediated. 4 Critical resolved. 9 Medium/Low in progress.",
        "dependency": "None",
        "validation_required": "No",
        "closure_evidence": "",
        "date_closed": "",
    },
    {
        "remediation_id": "REM-008",
        "finding_id": "FND-010",
        "owner": "Alice Johnson",
        "action_plan": "1. Evaluate SCIM integration options with HR system. 2. Configure SCIM provisioning. 3. Test de-provisioning workflow. 4. Set SLA of 2 hours. 5. Create alerting for de-provisioning failures. 6. Train HR team.",
        "target_date": "2026-03-15",
        "current_status": "Open",
        "progress_notes": "SCIM integration scoped. IT vendor assessment in progress.",
        "dependency": "HR system API access",
        "validation_required": "Yes",
        "closure_evidence": "",
        "date_closed": "",
    },
]

# ---------------------------------------------------------------------------
# Exceptions  (5 rows)
# ---------------------------------------------------------------------------
EXCEPTIONS = [
    {
        "exception_id": "EXC-001",
        "related_control_id": "NIST-AC-3",
        "related_finding_id": "FND-001",
        "exception_reason": "Legacy application does not support individual admin accounts. Shared account is required by the application architecture.",
        "business_justification": "Critical internal tooling required for 24/7 operations. Migration to new platform budgeted for Q2 2026.",
        "compensating_controls": "Session logging via PAM tool; password rotated after each use; shared account access restricted to 3 senior admins.",
        "risk_acceptance_owner": "Bob Martinez",
        "approval_status": "Approved",
        "expiration_date": "2026-06-30",
        "review_date": "2026-03-31",
        "notes": "Exception approved by CISO 2026-01-05. Must be resolved upon platform migration.",
    },
    {
        "exception_id": "EXC-002",
        "related_control_id": "HIPAA-164.308a",
        "related_finding_id": "FND-005",
        "exception_reason": "2025 risk assessment delayed due to GRC team resource constraints and system owner availability during Q4.",
        "business_justification": "Assessment will be completed by Feb 2026. Compensating controls in place during gap period.",
        "compensating_controls": "Previous 2024 risk assessment used as interim reference. Daily security monitoring via SIEM. No material changes to ePHI systems in 2025.",
        "risk_acceptance_owner": "Gina Torres",
        "approval_status": "Approved",
        "expiration_date": "2026-02-28",
        "review_date": "2026-01-31",
        "notes": "Approved by Compliance Director. Assessment must be completed by Feb 28.",
    },
    {
        "exception_id": "EXC-003",
        "related_control_id": "SOC2-CC7.2",
        "related_finding_id": "FND-009",
        "exception_reason": "Vulnerability remediation SLA policy is being drafted and requires legal and engineering review before publication.",
        "business_justification": "Policy development is in progress and expected to be finalized in Q1 2026.",
        "compensating_controls": "Vulnerabilities tracked in JIRA with manual SLA monitoring by security team lead.",
        "risk_acceptance_owner": "Carlos Lee",
        "approval_status": "Pending Approval",
        "expiration_date": "2026-03-31",
        "review_date": "2026-02-28",
        "notes": "Submitted to CISO office for review on 2026-01-10.",
    },
    {
        "exception_id": "EXC-004",
        "related_control_id": "CIS-1.1",
        "related_finding_id": "",
        "exception_reason": "Cloud asset discovery tool procurement delayed due to budget cycle. CMDB does not yet include cloud assets.",
        "business_justification": "Cloud discovery tool budgeted in FY2026 Q2. Manual cloud asset inventory maintained as interim measure.",
        "compensating_controls": "Monthly manual review of AWS Console asset inventory. Tagged resources reviewed via AWS Config.",
        "risk_acceptance_owner": "Bob Martinez",
        "approval_status": "Approved",
        "expiration_date": "2026-06-30",
        "review_date": "2026-04-30",
        "notes": "Approved pending tool procurement. Must integrate cloud assets by June 2026.",
    },
    {
        "exception_id": "EXC-005",
        "related_control_id": "HITRUST-09.ab",
        "related_finding_id": "FND-007",
        "exception_reason": "One vendor is a sole-source provider and is unresponsive to BAA execution requests. Legal escalation in progress.",
        "business_justification": "Vendor provides a critical data service with no alternative. Legal team has escalated to vendor legal counsel.",
        "compensating_controls": "Data sharing with this vendor is currently suspended pending BAA execution. Only aggregated, de-identified data shared as interim measure.",
        "risk_acceptance_owner": "Gina Torres",
        "approval_status": "Draft",
        "expiration_date": "2026-04-30",
        "review_date": "2026-02-15",
        "notes": "Legal escalation letter sent. CISO approval pending confirmation of data suspension.",
    },
]


# ---------------------------------------------------------------------------
# Load function called by app.py on first run
# ---------------------------------------------------------------------------
def load_seed_data():
    """Insert all seed records into the database."""
    init_db()
    if is_seeded():
        return  # Already seeded – do nothing

    controls_df   = pd.DataFrame(CONTROLS)
    evidence_df   = pd.DataFrame(EVIDENCE)
    findings_df   = pd.DataFrame(FINDINGS)
    remediation_df= pd.DataFrame(REMEDIATION)
    exceptions_df = pd.DataFrame(EXCEPTIONS)

    bulk_insert_df("controls",    controls_df,    if_exists="append")
    bulk_insert_df("evidence",    evidence_df,    if_exists="append")
    bulk_insert_df("findings",    findings_df,    if_exists="append")
    bulk_insert_df("remediation", remediation_df, if_exists="append")
    bulk_insert_df("exceptions",  exceptions_df,  if_exists="append")


if __name__ == "__main__":
    load_seed_data()
    print("✅ Seed data loaded successfully.")
